# Generated by Django 3.0.7 on 2020-07-14 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='course name')),
                ('description', models.TextField(max_length=300, verbose_name='course description')),
                ('price', models.FloatField(verbose_name='course price')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='username ')),
                ('adress', models.CharField(max_length=50, verbose_name='user adress')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Course')),
            ],
        ),
    ]
